### ISSUE TITLE
Returned handle cannot be used with "isatty"

### ISSUE THREAD

**Issue by Apollon77** [ChristianVisintin/termiWin#3]
The libmbus code uses "isatty" with the handle returned from "connect" to check if the connection is correct and to a serial device.

Because the handle you return is not really a handle, but the real handle is somewhere in your struct only this method returns an error.

Any idea how to fix this? Also overwrite isatty?

**Comment by veeso** [comment]
Well, this is pretty complicated I think.
In Linux when you initialize a communication with a serial device using the open() function and it returns to you a file descriptor (which is an integer), while in Windows the handler is stored in a HANDLE type variable, which is actually a void pointer.
Because of this, I don't think you coulduse the HANDLE of the COM structure to pass that control. 
If I were you I'd check if it is possible to skip that check.

**Comment by Apollon77** [comment]
I currently have ignored the check for windows.

In general the MSVC docs also have this function basically: https://msdn.microsoft.com/de-de/library/f4s0ddew.aspx and I found somewhere that it uses GetFileType() (https://msdn.microsoft.com/de-de/library/windows/desktop/aa364960(v=vs.85).aspx) and check for FILE_TYPE_CHAR.

So with this it could be added to your lib, or ?!

**Comment by Apollon77** [comment]
PS: As alternative I would need kind if an "getHandle" method to get the Handle out of your struct to do such calls directly

**Comment by veeso** [comment]
Ok, I've added getHandle() function to the library which returns the HANDLE from the COM structure

**Comment by Apollon77** [comment]
then I use that one :-) thank you. Will report results later

**Comment by Apollon77** [comment]
works. Maybe "getCurrentHandle" is better because in fact it can only habdle one serial connection, or ?!
